### PR TITLE
fix/battleReward/ItemData now is rewarded in correct inventory accord…

### LINKED ISSUE #118: [BUG] - Inventory Item assigned to wrong array
### What bug did you encounter?

Player defeated a slime and received a Small Health Potion. For some reason, this was saved to their equippable items array.

### What did you expect to happen?

This should have been assigned to the consumable items array.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by luigieai**
# Pull Request

## Description:

Fix a bug related to item drop in wrong inventory when you defeat a monster in a battle. The problem occours when you defeat a monster and win an item reward, the item always goes to equippable inventory, now the item is pushed to the right inventory.

## Related Issue:

Closes #118

### CODE REVIEW

File: src/modules/battle/results/battleVictory.ts [hunk 1]
```diff
@@ -59,8 +59,9 @@ export const battleVictory = async (
         monster.drops.items[
           Math.floor(Math.random() * monster.drops.items.length)
         ];
+
       const itemData = [...equippables, ...consumables, ...sellables].find(
-        (el) => (el.name = itemName)
+        (el) => el.name === itemName
```
Comment (nhcarrigan) [inline src/modules/battle/results/battleVictory.ts:64]: Hahaha omg the number of times I've made this bug 🤦🏻

**Review by nhcarrigan — APPROVED** [review]
Nice catch! Looks good to me.

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.
